---
- name: install Longhorn
  shell: kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v{{ longhorn_version }}/deploy/longhorn.yaml
  
- name: generate the multipath conf
  template:
    src: templates/multipath-conf.j2
    dest: "/etc/multipath.conf"
    mode: '0644'                     
    owner: root                      
    group: root 
    
- name: restart multipathd
  shell: systemctl restart multipathd.service
