---
- name: Longhorn config option
  debug: msg="install_package_longhorn = {{ install_package_longhorn }}"
  when: "inventory_hostname == groups['k8s_masters'][0]"

- name: install Longhorn
  include_tasks: longhorn.yml
  when: "inventory_hostname == groups['k8s_masters'][0] and install_package_longhorn|bool"
