# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cluster Builder
email: admin@idstudios.io
description: 'Automatically Deploy Kubernetes Container Orchestration Clusters into VMware Environments.'
url: 'https://cluster-builder.idstudios.io'
github_username: ids
future: true
excerpt_separator: '---'
plugins:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jemoji
sass:
    style: compressed
collections:
    docs: {output: true, permalink: '/docs/:path/'}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
include:
    - _pages
logo: /images/logo-2018-icon.png

# github.com/untra/polyglot
languages:
  - en
default_lang: en
exclude_from_localization:
  - bower_components
  - css
  - images
  - js
  - lib
  - script
parallel_localization: true

# Build settings
theme: minima
