#!/bin/bash

CLUSTER_NAME=$1

if [ -z CLUSTER_NAME ]; then
  echo "Cluster is invalid or unspecified."
  exit
fi
INVENTORY_FILE=./clusters/$CLUSTER_NAME/hosts
CLUSTER_TYPE=`sed -n '/^cluster_type=/ {s///p;q;}' $INVENTORY_FILE`

if [ "$CLUSTER_TYPE" == 'photon-swarm' ]; then
  echo ""
elif [ "$CLUSTER_TYPE" == 'centos-dcos' ]; then
  echo ""
elif [ "$CLUSTER_TYPE" == 'centos-swarm' ]; then
  ansible-playbook -i $INVENTORY_FILE ansible/rhel-update.yml
elif [ "$CLUSTER_TYPE" == 'centos-ucp' ]; then
  ansible-playbook -i $INVENTORY_FILE ansible/rhel-update.yml
elif [ "$CLUSTER_TYPE" == 'rhel-swarm' ]; then
  ansible-playbook -i $INVENTORY_FILE ansible/rhel-update.yml
elif [ "$CLUSTER_TYPE" == 'rhel-ucp' ]; then
  ansible-playbook -i $INVENTORY_FILE ansible/rhel-update.yml
fi