#!/bin/bash
INVENTORY_FILE=$1
ACTION=$2

function show_usage () {
  echo "usage: $ bash esxi-control <inventory-file> <action: start|suspend|stop|destroy>"
  exit 1
}

if [ -z $INVENTORY_FILE ]; then 
  echo
  echo "Inventory file not specified!"
  show_usage
fi

if [ ! -f $INVENTORY_FILE ]; then
  echo
  echo "Unable to find inventory file @: ${INVENTORY_FILE}"
  exit 1
fi

if [ -z $ACTION ]; then 
  echo
  echo "Action not specified!"
  show_usage
fi

CLUSTER_TYPE=`sed -n '/^cluster_type=/ {s///p;q;}' $INVENTORY_FILE`
VMWARE_TARGET=`sed -n '/^vmware_target=/ {s///p;q;}' $INVENTORY_FILE`
  
if [ "$ACTION" == "start" ] || [ "$ACTION" == "stop" ] || [ "$ACTION" == "suspend" ] || [ "$ACTION" == "destroy" ]; then
  ansible-playbook -i $INVENTORY_FILE ansible/$VMWARE_TARGET-control-vms.yml --e "vm_action=$ACTION"
  vmrun list
else
  echo
  echo "Invalid: You must specify an action that is one of: start, stop, suspend or destroy"
  echo
fi