#!/bin/bash
INVENTORY_FILE=$1
ACTION=$2
ANSIBLE_DISPLAY_SKIPPED_HOSTS=false

function show_usage () {
  echo "usage: $ bash esxi-control <inventory-file> <action: start|suspend|stop|destroy>"
  exit 1
}

if [ -z $INVENTORY_FILE ]; then 
  echo
  echo "Cluster package not specified!"
  show_usage
fi

INVENTORY_FILE=./clusters/$INVENTORY_FILE/hosts

if [ ! -f $INVENTORY_FILE ]; then
  echo
  echo "Unable to find inventory file @: ${INVENTORY_FILE}"
  exit 1
fi

if [ -z $ACTION ]; then 
  echo
  echo "Action not specified!"
  show_usage
fi

PLATFORM=`uname -ra`
VMRUN_CMD=vmrun
if [[ $PLATFORM == *"Microsoft"* ]]; then 
  export ANSIBLE_CONFIG=$PWD/ansible.cfg
  VMRUN_CMD=vmrun.exe
fi 

CLUSTER_TYPE=`sed -n '/^cluster_type=/ {s///p;q;}' $INVENTORY_FILE | tr -d '\n' | tr -d '\r'`
VMWARE_TARGET=`sed -n '/^vmware_target=/ {s///p;q;}' $INVENTORY_FILE | tr -d '\n' | tr -d '\r'`
CLUSTER_PROTECTED=`sed -n '/^protected=/ {s///p;q;}' $INVENTORY_FILE | tr -d '\n' | tr -d '\r'`

if [ "$VMWARE_TARGET" == "fusion" ]; then
  VMWARE_TARGET=desktop
fi

if [ "$ACTION" == "destroy" ] && [ "$CLUSTER_PROTECTED" == "true" ]; then
  echo
  echo "Destroy Blocked!"
  echo "Cluster Protected: destroy may not be used on clusters where protected=true" 
  echo "Remove this flag from the cluster hosts file to delete the cluster when all jobs have been transitioned."
  echo
  exit 1
fi  

if [ "$ACTION" == "start" ] || [ "$ACTION" == "stop" ] || [ "$ACTION" == "suspend" ] || [ "$ACTION" == "destroy" ]; then
  ansible-playbook -i $INVENTORY_FILE ansible/$VMWARE_TARGET-control-vms.yml --e "vm_action=$ACTION"
  ${VMRUN_CMD} list
else
  echo
  echo "Invalid: You must specify an action that is one of: start, stop, suspend or destroy"
  echo
fi