#!/bin/bash

INVENTORY_FILE=$1
if [ -z INVENTORY_FILE ]; then
  read -s "Enter the swarm cluster inventory file: " INVENTORY_FILE
fi

if [ ! -f $INVENTORY_FILE ]; then
  echo
  echo "Unable to find inventory file @: ${INVENTORY_FILE}\n"
  exit 1
fi

CLUSTER_TYPE=`sed -n '/^cluster_type=/ {s///p;q;}' $INVENTORY_FILE`
OVA_TEMPLATE_FILE=`sed -n '/^ova_template=/ {s///p;q;}' $INVENTORY_FILE`

if [ "$CLUSTER_TYPE" == 'photon-swarm' ]; then
  CLUSTER_TYPE_NAME='PhotonOS Swarm'
elif [ "$CLUSTER_TYPE" == 'centos-dcos' ]; then
  CLUSTER_TYPE_NAME='DC/OS Cluster'
fi

echo "Validating SUDO session (Enter local SUDO password for VMware network management if prompted)"
sudo date

echo "Creating the Fusion VMs and configuring the network for static IP assignment..."
ansible-playbook -i $INVENTORY_FILE ansible/fusion-create-vms.yml 
if [ $? -eq 0 ]; then
  echo "Configuring the ${CLUSTER_TYPE_NAME} Cluster..."
  ansible-playbook -i $INVENTORY_FILE ansible/$CLUSTER_TYPE.yml 
  if [ $? -eq 0 ]; then
    sleep 5s
    cd client-certs
    bash test-swarm
    cd ..
    echo
    echo "SUCCESS: Fusion ${CLUSTER_TYPE_NAME} created!"
  else
    echo "FAIL: Fusion ${CLUSTER_TYPE_NAME} creation failed!"
  fi

else
  echo "There was a problem creating the VMs"
fi
