// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.landoop.social.reddit.post
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class reddit_post : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""reddit_post"",""namespace"":""com.landoop.social.reddit.post"",""fields"":[{""name"":""created_utc"",""type"":""int""},{""name"":""ups"",""type"":""int""},{""name"":""subreddit_id"",""type"":""string""},{""name"":""link_id"",""type"":""string""},{""name"":""name"",""type"":""string""},{""name"":""score_hidden"",""type"":""int""},{""name"":""author_flair_css_class"",""type"":[""null"",""string""]},{""name"":""author_flair_text"",""type"":[""null"",""string""]},{""name"":""subreddit"",""type"":""string""},{""name"":""id"",""type"":""string""},{""name"":""removal_reason"",""type"":[""null"",""string""]},{""name"":""gilded"",""type"":""int""},{""name"":""downs"",""type"":""int""},{""name"":""archived"",""type"":""boolean""},{""name"":""author"",""type"":""string""},{""name"":""score"",""type"":""int""},{""name"":""retrieved_on"",""type"":""int""},{""name"":""body"",""type"":""string""},{""name"":""distinguished"",""type"":[""null"",""string""]},{""name"":""edited"",""type"":""int""},{""name"":""controversiality"",""type"":""boolean""},{""name"":""parent_id"",""type"":""string""}]}");
		private int _created_utc;
		private int _ups;
		private string _subreddit_id;
		private string _link_id;
		private string _name;
		private int _score_hidden;
		private string _author_flair_css_class;
		private string _author_flair_text;
		private string _subreddit;
		private string _id;
		private string _removal_reason;
		private int _gilded;
		private int _downs;
		private bool _archived;
		private string _author;
		private int _score;
		private int _retrieved_on;
		private string _body;
		private string _distinguished;
		private int _edited;
		private bool _controversiality;
		private string _parent_id;
		public virtual Schema Schema
		{
			get
			{
				return reddit_post._SCHEMA;
			}
		}
		public int created_utc
		{
			get
			{
				return this._created_utc;
			}
			set
			{
				this._created_utc = value;
			}
		}
		public int ups
		{
			get
			{
				return this._ups;
			}
			set
			{
				this._ups = value;
			}
		}
		public string subreddit_id
		{
			get
			{
				return this._subreddit_id;
			}
			set
			{
				this._subreddit_id = value;
			}
		}
		public string link_id
		{
			get
			{
				return this._link_id;
			}
			set
			{
				this._link_id = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public int score_hidden
		{
			get
			{
				return this._score_hidden;
			}
			set
			{
				this._score_hidden = value;
			}
		}
		public string author_flair_css_class
		{
			get
			{
				return this._author_flair_css_class;
			}
			set
			{
				this._author_flair_css_class = value;
			}
		}
		public string author_flair_text
		{
			get
			{
				return this._author_flair_text;
			}
			set
			{
				this._author_flair_text = value;
			}
		}
		public string subreddit
		{
			get
			{
				return this._subreddit;
			}
			set
			{
				this._subreddit = value;
			}
		}
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string removal_reason
		{
			get
			{
				return this._removal_reason;
			}
			set
			{
				this._removal_reason = value;
			}
		}
		public int gilded
		{
			get
			{
				return this._gilded;
			}
			set
			{
				this._gilded = value;
			}
		}
		public int downs
		{
			get
			{
				return this._downs;
			}
			set
			{
				this._downs = value;
			}
		}
		public bool archived
		{
			get
			{
				return this._archived;
			}
			set
			{
				this._archived = value;
			}
		}
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				this._author = value;
			}
		}
		public int score
		{
			get
			{
				return this._score;
			}
			set
			{
				this._score = value;
			}
		}
		public int retrieved_on
		{
			get
			{
				return this._retrieved_on;
			}
			set
			{
				this._retrieved_on = value;
			}
		}
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				this._body = value;
			}
		}
		public string distinguished
		{
			get
			{
				return this._distinguished;
			}
			set
			{
				this._distinguished = value;
			}
		}
		public int edited
		{
			get
			{
				return this._edited;
			}
			set
			{
				this._edited = value;
			}
		}
		public bool controversiality
		{
			get
			{
				return this._controversiality;
			}
			set
			{
				this._controversiality = value;
			}
		}
		public string parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				this._parent_id = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.created_utc;
			case 1: return this.ups;
			case 2: return this.subreddit_id;
			case 3: return this.link_id;
			case 4: return this.name;
			case 5: return this.score_hidden;
			case 6: return this.author_flair_css_class;
			case 7: return this.author_flair_text;
			case 8: return this.subreddit;
			case 9: return this.id;
			case 10: return this.removal_reason;
			case 11: return this.gilded;
			case 12: return this.downs;
			case 13: return this.archived;
			case 14: return this.author;
			case 15: return this.score;
			case 16: return this.retrieved_on;
			case 17: return this.body;
			case 18: return this.distinguished;
			case 19: return this.edited;
			case 20: return this.controversiality;
			case 21: return this.parent_id;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.created_utc = (System.Int32)fieldValue; break;
			case 1: this.ups = (System.Int32)fieldValue; break;
			case 2: this.subreddit_id = (System.String)fieldValue; break;
			case 3: this.link_id = (System.String)fieldValue; break;
			case 4: this.name = (System.String)fieldValue; break;
			case 5: this.score_hidden = (System.Int32)fieldValue; break;
			case 6: this.author_flair_css_class = (System.String)fieldValue; break;
			case 7: this.author_flair_text = (System.String)fieldValue; break;
			case 8: this.subreddit = (System.String)fieldValue; break;
			case 9: this.id = (System.String)fieldValue; break;
			case 10: this.removal_reason = (System.String)fieldValue; break;
			case 11: this.gilded = (System.Int32)fieldValue; break;
			case 12: this.downs = (System.Int32)fieldValue; break;
			case 13: this.archived = (System.Boolean)fieldValue; break;
			case 14: this.author = (System.String)fieldValue; break;
			case 15: this.score = (System.Int32)fieldValue; break;
			case 16: this.retrieved_on = (System.Int32)fieldValue; break;
			case 17: this.body = (System.String)fieldValue; break;
			case 18: this.distinguished = (System.String)fieldValue; break;
			case 19: this.edited = (System.Int32)fieldValue; break;
			case 20: this.controversiality = (System.Boolean)fieldValue; break;
			case 21: this.parent_id = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
