---
- name: install metallb
  shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
  when: "metallb_address_range is defined"

- name: give metalLB a few seconds
  pause:
    seconds: 5
  when: "metallb_address_range is defined" 

- name: wait for metallb 
  shell: kubectl wait -n metallb-system pod -l app=metallb --for condition=Ready --timeout={{ pod_readiness_timeout }}
  when: "metallb_address_range is defined" 

- name: generate the metalLB pool
  template:
    src: templates/k8s-metallb-pool.j2
    dest: "{{ target_dest_folder }}/metallb-pool.yml"
  when: "metallb_address_range is defined" 

- name: install metalLB IP Pool
  shell: kubectl apply -f {{ target_dest_folder }}/metallb-pool.yml
  when: "metallb_address_range is defined"
