---
- name: copy custom cert to server
  ansible.builtin.copy:
    src: "{{ sealedsecrets_cert_folder}}/{{ sealedsecrets_cert_file }}"
    dest: /root/{{ sealedsecrets_cert_file}}
    owner: root
    group: root
    mode: '0644'

- name: copy custom key to server
  ansible.builtin.copy:
    src: "{{ sealedsecrets_cert_folder}}/{{ sealedsecrets_key_file }}"
    dest: /root/{{ sealedsecrets_key_file}}
    owner: root
    group: root
    mode: '0644'

- name: create namespace
  shell: kubectl create ns {{ sealedsecrets_ns }}

- name: create cluster secret key
  shell: kubectl -n sealed-secrets create secret tls cluster-sealedsecret-keys --cert="{{ sealedsecrets_cert_file }}" --key="{{ sealedsecrets_key_file }}"

- name: label cluster secret key as active
  shell: kubectl -n sealed-secrets label secret cluster-sealedsecret-keys sealedsecrets.bitnami.com/sealed-secrets-key=active

- name: install Sealed Secrets Helm Repo
  shell: /usr/local/bin/helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets

- name: install Sealed Secrets
  shell: "/usr/local/bin/helm upgrade --install sealed-secrets-controller sealed-secrets/sealed-secrets --namespace={{ sealedsecrets_ns }} --version {{ sealedsecrets_version }}"
