#!/bin/bash

OP_KEY=~/.ssh/id_rsa.pub 
if [ ! -f keys/authorized_keys ]; then
  if [ ! -f $OP_KEY ]; then
    echo 
    echo "Error: 'authorized_keys' must be set before the image is built, run 'bash keys/set-key' to use your current public key"
    echo "Unable to find ${OP_KEY}, can't auto-set the authorized_keys!"
    echo "Make sure keys/authorized_keys exists and has the cluster-builder operator key."
    exit 1
  fi
  bash keys/set-key
fi

START_TIME=$SECONDS

rm -rf ./cluster-node
PACKER_CMD="packer build rockylinux9.pkr.hcl"

echo 'Building VM image:' 
eval $PACKER_CMD

mv ./cluster-node/*.ova ./output_ovas
rm -rf ./cluster-node

ELAPSED_TIME=$(($SECONDS - $START_TIME))
echo "Template image built in: $(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) sec" 
echo
