---
- hosts: vmware_vms
  gather_facts: false
  roles: 
    - config

  tasks:    
  - name: start/stop/suspend the VMs on macOS/Linux
    local_action:
      module: shell
      _raw_params: vmrun {{ vm_action }} {{ desktop_vm_folder }}/{{ vm_folder_name }}/{{ inventory_hostname }}.vmx nogui
    when: vm_action != 'destroy' and platform != "windows"
    retries: 5
    delay: 5
    register: result
    until: result.rc is defined and result.rc == 0

  - name: start/stop/suspend the VMs 
    local_action:
      module: shell
      _raw_params: vmrun.exe {{ vm_action }} {{ desktop_vm_folder }}/{{ vm_folder_name }}/{{ inventory_hostname }}.vmx nogui
    when: vm_action != 'destroy' and platform == "windows"

  - name: stop the VMs for destruction on macOS/Linux
    local_action:
      module: shell
      _raw_params: vmrun stop {{ desktop_vm_folder }}/{{ vm_folder_name }}/{{ inventory_hostname }}.vmx nogui
    ignore_errors: true
    when: vm_action == 'destroy' and platform != "windows"
    retries: 5
    delay: 5
    register: result
    until: result.rc is defined and result.rc == 0
 
  - name: destroy the VMs on macOS/Linux
    local_action:
      module: shell
      _raw_params: rm -rf {{ desktop_vm_folder }}/{{ vm_folder_name }}
    when: vm_action == 'destroy' and platform != "windows"

  - name: stop the VMs for destruction on Windows
    local_action:
      module: shell
      _raw_params: vmrun.exe stop {{ desktop_vm_folder }}/{{ vm_folder_name }}/{{ inventory_hostname }}.vmx nogui
    ignore_errors: true
    when: vm_action == 'destroy' and platform == "windows"
  
  - name: destroy the VMs 
    local_action:
      module: shell
      _raw_params: rm -rf {{ desktop_vm_folder }}/{{ vm_folder_name }}
    when: vm_action == 'destroy' and platform == "windows"
