---
# This playbook adds Ubuntu 24.04 k8s nodes on Proxmox VE

- hosts: k8s_masters:k8s_workers
  gather_facts: false
  remote_user: root
  any_errors_fatal: true
  vars:
    kube_config_file: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/kubeconfig"
  roles:
    - role: config
    - role: ubuntu


  