---
# This playbook creates Ubuntu 24.04 on Proxmox

- hosts: k8s_masters:k8s_workers
  become: true
  gather_facts: false
  remote_user: root
  any_errors_fatal: true
  vars:
    kube_config_file: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/kube-config"
  roles:
    - role: common
    - role: common-cluster
    - role: k8s-init
    - role: k8s-cni
    - role: k8s-masters
    - role: k8s-workers
    - role: k8s-ingress
    - role: k8s-dash
    - role: k8s-storage
    - role: k8s-inspect


  