---
# This playbook creates a Rocky 9.4 Kubernetes

- hosts: all
  gather_facts: false
  any_errors_fatal: true
  remote_user: admin
  become: true
  vars:
    kube_config_file: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/kube-config"
  roles:
    - role: config
    - role: rocky9
    - role: k8s
    - role: metallb
    - role: nginx
    - role: dashboard
    - role: longhorn
    - role: flux
    - role: sealed-secrets
    - role: k8s-inspect


  