---
# This playbook creates a Rocky 9.4 Kubernetes

- hosts: all
  become: true
  gather_facts: false
  any_errors_fatal: true
  remote_user: admin
  vars:
    kube_config_file: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/kube-config"
  roles:
  - role: config
  - role: rocky9
  - role: k8s


  