---
# This playbook creates a Rocky 9.4 Kubernetes

- hosts: all
  become: true
  gather_facts: false
  any_errors_fatal: true
  remote_user: admin
  vars:
    kube_config_file: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/kube-config"
  roles:
  - role: common
  - role: common-cluster
  - role: rocky9
  - role: k8s-init
  - role: k8s-cni
  - role: k8s-masters
  - role: k8s-workers
#  - role: k8s-dash
  - role: k8s-inspect


  