- name: install Dashboard Helm Repo
  shell: /usr/local/bin/helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
  when: "inventory_hostname == groups['k8s_masters'][0]"

- name: install Kubernetes Dashboard
  shell: /usr/local/bin/helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
  when: "inventory_hostname == groups['k8s_masters'][0]"

- name: list all running pods
  shell: kubectl get pods --all-namespaces
  register: final_pods_out
  when: "inventory_hostname == groups['k8s_masters'][0]"

- debug: msg="{{ final_pods_out.stdout_lines }}"
  when: "inventory_hostname == groups['k8s_masters'][0]"
