---
- name: install canal CNI 
  shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ canal_version }}/manifests/canal.yaml
  
- name: allow the CNI time to deploy
  pause:
    seconds: 20

- name: wait for canal CNI on masters
  shell: kubectl wait -n kube-system pod -l k8s-app=canal --for condition=Ready --timeout={{ pod_readiness_timeout }}
  
- name: display cluster master node status
  shell: kubectl get nodes
  register: final_nodes_out
  
- debug: msg="{{ final_nodes_out.stdout_lines }}"
  

