- name: generate the kubeadm yaml configuration
  template:
    src: templates/k8s-kubeadm.j2
    dest: "{{ target_dest_folder }}/kube-adm.yml"

- name: ensure the kubelet is enabled
  shell: systemctl enable kubelet

- debug: msg="intializing kubeadm cluster..."

- name: initialize cluster on first master
  shell: "kubeadm init --config {{ target_dest_folder }}/kube-adm.yml --upload-certs > /root/kube_init_output"
  ignore_errors: false

- name: create master join command
  shell: "grep -A 4 \"You can now join any number of control-plane nodes\" /root/kube_init_output | sed '1,2d' > /root/master_join_cmd"
  ignore_errors: true

- name: get master join command
  shell: "cat /root/master_join_cmd"
  register: master_join_cmd
  ignore_errors: true

- name: kubeadm master join command
  debug: msg="{{ master_join_cmd.stdout }}"
  ignore_errors: true

- name: get worker join command
  shell: "kubeadm token create --print-join-command"
  register: kubeadm_join_cmd

- name: kubeadm worker join command
  debug: msg="{{ kubeadm_join_cmd.stdout }}"

- name: export worker join command to {{ target_dest_folder }}/join_cmd
  shell: "kubeadm token create --print-join-command > /root/join_cmd "
  when: "remote_user == 'root'"

- name: export worker join command to {{ target_dest_folder }}/join_cmd
  shell: "kubeadm token create --print-join-command > {{ target_dest_folder }}/join_cmd "
  when: "remote_user != 'root'"

- name: setup kubectl configuration
  shell: rm -rf $HOME/.kube && mkdir -p $HOME/.kube && cp /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config

- name: fetch the kube_init_output file
  fetch:
    src: "{{ target_dest_folder }}/kube_init_output"
    dest: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/"
    flat: yes     

- name: fetch the master_join_cmd file
  fetch:
    src: "{{ target_dest_folder }}/master_join_cmd"
    dest: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/"
    flat: yes     
  ignore_errors: true

- name: fetch the join_cmd file
  fetch:
    src: "{{ target_dest_folder }}/join_cmd"
    dest: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/"
    flat: yes     

- name: fetch the admin.conf file
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/"
    flat: yes     

- name: fetch the kube config from the first master
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/kubeconfig"
    flat: yes     

- name: get master node status
  shell: kubectl get nodes
  register: master_node_out

- debug: msg="{{ master_node_out.stdout_lines }}"

