#- name: ensure pki folder exists
#  shell: mkdir -p /etc/kubernetes/pki/

#- name: ensure pki/etcd folder exists
#  shell: mkdir -p /etc/kubernetes/pki/etcd

#- name: copy the PKI certs to the other masters
#  copy:
#    dest: /etc/kubernetes/pki/{{ item }}
#    src: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/pki/{{ item }}"
#    mode: 644
#  with_items:
#    - ca.crt  
#    - front-proxy-ca.crt  
#    - etcd/ca.crt
#    - front-proxy-client.crt  
#    - apiserver.crt  
#    - apiserver-kubelet-client.crt  

- name: copy the master_join_cmd
  copy:
    dest: /root/
    src: ../clusters/{{ cluster_pkg_folder }}/master_join_cmd
    mode: 766

- name: start kubelet on other master nodes
  service:
    name: kubelet
    state: restarted
    enabled: yes

- name: pause to give kubelet time to initialize
  pause:
    seconds: 30

- name: join other master to cluster
  shell: "/root/master_join_cmd"
  register: master_join

- name: master join result
  debug: msg="{{ master_join.stdout_lines }}"
